family: sd
sd:
  variant: v1
  v2_highres: false
  prompt: a photo of cute moon bear
  scale: 100.0
  precision: autocast
  dir: ./results2/moon_bear/lora/final_lora.safetensors
  alpha: 0.3
lr: 0.05
n_steps: 10000
vox:
  model_type: V_SD
  bbox_len: 1.0
  grid_size:
  - 100
  - 100
  - 100
  step_ratio: 0.5
  density_shift: -1.0
  ray_march_weight_thres: 0.0001
  c: 4
  blend_bg_texture: false
  bg_texture_hw: 4
pose:
  rend_hw: 64
  FoV: 60.0
  R: 1.5
emptiness_scale: 10
emptiness_weight: 10000
emptiness_step: 0.5
emptiness_multiplier: 20.0
depth_weight: 0
var_red: true
exp_dir: ./results2
save_name: moon_bear
ti_step: 500
pt_step: 500
initial: bear
random_seed: 0
semantic_model: SD
bg_preprocess: true
num_initial_image: 4
